#!/bin/sh

. $HOME/.cache/wal/colors.sh

cat << EOF > $HOME/.config/dunst/dunstrc
[global]
    monitor = 0
    sort = yes
    idle_threshold = 120
    font = Noto Sans Regular 11
    line_height = 0
    markup = yes
    format = "<b>%s</b>\n%b"
    alignment = left
    show_age_threshold = 60
    word_wrap = yes
    ellipsize = middle
    ignore_newline = no
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = yes
    icon_position = left
    max_icon_size = 32
    
    sticky_history = yes
    history_length = 20
    
    dmenu = /usr/bin/dmenu -p dunst:
    browser = /usr/bin/firefox -new-tab
    title = Dunst
    class = Dunst
    startup_notification = false
    verbosity= mesg
    corner_radius = 0
    force_xinerama = false
    follow = keyboard
    mouse_left_click = close_current
    mouse_middle_click = do_action
    mouse_right_click = close_all
    geometry = "300x5-30-30"
    indicate_hidden = yes
    shrink = no
    transparency = 16
    notification_height = 0
    separator_height = 2
    padding = 8
    horizontal_padding = 8
    frame_width = 1
[experimental]
    per_monitor_dpi = false
[shortcuts]
    close = ctrl+space
    close_all = ctrl+shift+space
    history = ctrl+grave
    context = ctrl+shift+period
frame_color = "${cursor}"
separator_color = "${foreground}"
[base16_low]
    msg_urgency = low
    background = "${color0}"
    foreground = "${color1}"
[base16_normal]
    msg_urgency = normal
    background = "${background}"
    foreground = "${foreground}"
[base16_critical]
    msg_urgency = critical
    background = "${color15}"
    foreground = "${color14}"
EOF
