#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

# $HOME/.config/bspwm/modules/double-borders;
# I do not like my windows flashing every time I change focus :/

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         3
bspc config window_gap           20

bspc config top_padding          40
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true


bspc rule -a firefox desktop='^2'
bspc rule -a spotify desktop='^10'

