#! /bin/bash

outer='0x202020'  # outer
inner1='0xC1B491'  # focused
inner2='0xC1B491'  # normal

bspc config top_padding          37
bspc config bottom_padding       0

bspc config border_width 20

draw() { chwb2 -I "$inner" -O "$outer" -i "4" -o "9" "$@" >/dev/null 2>&1 ; }

targets() {
 	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

{ echo; bspc subscribe node_geometry node_focus; } |
 	while read -r _; do
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets normal)"
	done

